version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.37
    steps:
      - checkout
      - run: cargo build
  test:
    docker:
      - image: circleci/rust:1.37
    steps:
      - checkout
      - run: cargo test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test